script_name: "Y14_1213"
unique_id: "attention1ep1"
model_name: "bert"
dataset_dir: "data/pickle/Y14"
model_dir: "data/model/Y14"
model_config_path: "config/ys/model/bert.yml"
preprocessing_type: "bert"
target_type: "analytic"
loss: "attention"
learning_rate: 0.00005
batch_size: 8
epoch: 100
wandb: true
wandb_entity: "ekupura"
wandb_project_name: "0529"
wandb_group: "Y14_1213"
parallel: true
attention_lambda: 10.0