script_name: "Y14_1213"
unique_id: "lstm"
model_name: "lstm"
dataset_dir: "data/pickle/Y14"
model_dir: "data/model/Y14"
model_config_path: "config/ys/model/lstm.yml"
preprocessing_type: "fasttext"
target_type: "analytic"
loss: "mse"
learning_rate: 0.001
batch_size: 4
epoch: 100
wandb: true
wandb_entity: "ekupura"
wandb_project_name: "0510"
wandb_group: "Y14_1213"
parallel: true