script_name: "Y14_1213"
unique_id: "analytic"
model_name: "bert"
dataset_dir: "data/pickle/Y14"
model_dir: "data/model/Y14"
model_config_path: "config/ys/model/bert.yml"
preprocessing_type: "bert"
target_type: "analytic"
loss: "mse"
learning_rate: 0.00001
batch_size: 32
epoch: 200
wandb: true
wandb_entity: "ekupura"
wandb_project_name: "0529"
wandb_group: "Y14_1213"
parallel: true