version: '3'
services:
  gpu:
    build: ./docker
    # please set unique container name
    container_name: sas
    # please set unique port number (49152–65535)
    ports:
      - "54321:22"
    volumes:
      - ./src:/mnt/src
    tty: true
    shm_size: '2gb'
    entrypoint: "/bin/bash /cmd.sh"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
