preprocess_name: "Y14_1213"
script_path: "data/data_ys/Y14/Y14_1-2_1_3.json"
dataset_dir: "data/pickle/Y14"
prompt_path: "config/prompt/Y14_1213.yml"
contamination_path: "config/contamination/Y14_1213.yml"
dataset_type: "ys"
download_ft: false