script_name: "toppan-1"
model_name: "bert"
dataset_dir: "data/pickle/toppan"
model_dir: "data/model/toppan/crossvalid"
preprocessing_type: "bert"
target_type: "analytic"
loss: "mse"
learning_rate: 0.00001
batch_size: 4
epoch: 200
wandb: true
wandb_entity: "ekupura"
wandb_project_name: "toppan-crossvalid"
wandb_group: "bert"
parallel: true
