script_name: "Y14_2115_supervising"
model_name: "bert"
dataset_dir: "data/pickle/Y14"
model_dir: "data/model/Y14"
eval_dir: "data/eval/Y14"
model_config_path: "config/ys/model/bert.yml"
preprocessing_type: "bert"
attribution: true
cluster_dir: "data/cluster/Y14"
point_type: "counter"
gold_cluster_dir: "data/cluster/Y14/gold_dict"
step_size: 512