script_name: "Y14_1213"
model_name: "lstm"
dataset_dir: "data/pickle/Y14"
model_dir: "data/model/Y14"
eval_dir: "data/eval/Y14"
model_config_path: "config/ys/model/lstm.yml"
preprocessing_type: "fasttext"
target_type: "analytic"
unique_id: "lstm"
attribution: true
counterfactual: false
affine_type: "embedding"
cluster_dir: "data/cluster/Y14"
point_type: "counter"
gold_cluster_dir: "data/cluster/Y14/gold_dict"
